jdk.xml.xpathExprOpLimit=0
jdk.xml.xpathExprGrpLimit=0
jdk.xml.xpathTotalOpLimit=0
jdk.xml.entityExpansionLimit=0
jdk.xml.totalEntitySizeLimit=0
jdk.xml.maxOccurLimit=0
jdk.xml.enableExtensionFunctions=true
