[[advanced-client-api]]
## Deep Dive Into the RavenDB Client API


In this chapter, we're going to take a deep dive into how the client API works. We're going to show mostly C# code examples, but the
same concepts apply to any of the RavenDB client APIs, regardless of platform, with minor changes needed to make things applicable.

There are still some concepts that we haven't gotten around to (clustering or indexing, for example), which will be covered in
their own chapters. But the client API is rich and has a lot of useful functionality on its own, quite aside from the server-side behavior.

We already looked into `DocumentStore` and the `session`, the basic building blocks of CRUD in RavenDB. But in this chapter, we're going to 
look beyond the obvious and into the more advanced features.

One thing we'll _not_ talk about in this chapter is querying. We'll cover that extensively in <<querying-in-ravendb>>, so let's keep it there. 
You already know the basics of querying in RavenDB, but there's a _lot_ more power for you to discover.

This chapter is going to contain a large number of code examples, and it will discuss the nitty-gritty details of using the client. It's 
divided into brief sections each dealing with a specific feature or behavior. I suggest reading this over to note the capabilities of RavenDB
and coming back to it as needed in your application.

For the rest of this chapter, we'll use the classes shown in <<simplified-help-desk-model>> as our model, using a simplified help desk as 
our example.

[[simplified-help-desk-model]]
.Simplified Help Desk sample model
[source,csharp]
----
public class Customer
{
	public string Id { get; set; }
	public string Name { get; set; }
}

public class SupportCall
{
	public string Id { get; set; }
	public string CustomerId { get; set; }
	public DateTime Started { get;set; }
	public DateTime? Ended { get;set; }
	public string Issue { get; set; }
	public int Votes { get; set; }
	public List<string> Comments { get; set; }
}
----

== Writing documents

Writing documents in RavenDB is easy, as we saw in <<zero-to-ravendb>>.
If we want to create a new support call, we can use the code in <<create-support-call-session>> to do so.

[[create-support-call-session]]
.Creating a new support call using the session
[source,csharp]
----
using (var session = store.OpenSession())
{
	var call = new SupportCall
	{
		Started = DateTime.UtcNow,
		Issue = customerIssue,
		CustomerId = customerId
	};
	session.Store(call);
	session.SaveChanges();
}
----

This is the basic behavior of RavenDB and how you would typically work with saving data. But there are lot of additional things that we can do 
when writing data. For example, let's say the user might have sent us some screenshots that we want to include in the support call.
.The `async` API mirrors the synchronous one
****
Most of the code samples use the synchronous API because it is simpler. With the `async` API, you'll need to add `await`, sometimes use
`ConfigureAwait(false)`, and consider cancellation tokens. The goal here is to explain how RavenDB _works_, rather than to cover every 
detail of the API.

You can easily switch from `OpenSession` to `OpenAsyncSession` to use the `async` API. The main difference is that you call 
`await session.SaveChangesAsync()` instead of `session.SaveChanges()`.

Hint: If you see an API call in the `async` session that does _not_ use the `Async` suffix and returns a task, you can be sure it operates
purely in memmory. For example, both synchronous and `async` sessions have a `void Delete(string documentId)` method. Because the `async` version does not have a `Task DeleteAsync(string documentId)` method, it simply updates the session's internal bookkeeping. The actual deletion on the server will occur as part of the `SaveChangesAsync()` call.
****

=== Working with attachments

We already talked in depth about attachments in <<documents-extensions>>. I cover them here as well to look at them from the client API
perspective, not just how they work on the server. You can add attachments to a RavenDB document to store binary data related to that document. 
Let's assume the user sent us a screenshot of the problem along with the call. <<save-attachments-opening-support-call>> shows how we can 
store and retrieve the attachments.

[[save-attachments-opening-support-call]]
.Saving attachments to RavenDB as part of opening the support call
[source,csharp]
----
using (var session = store.OpenSession())
{
	var call = new SupportCall
	{
		Started = DateTime.UtcNow,
		Issue = customerIssue,
		CustomerId = customerId
	};
	session.Store(call);

	foreach (var file in attachedFiles)
	{
		session.Advanced.StoreAttachment(call, file.Name, 
			file.OpenStream());
	}

	session.SaveChanges();
}
----

Note that we're using the session to store both the support call document and any attachments the user might have sent. 
An attachment is basically a file name and a stream that will be sent to the server (with an optional content type). When the call 
to `SaveChanges` is made, the RavenDB client API
will send both the new document and all of its attachments to the server in a single call, which will be treated as a transaction. 
Both the document and the attachments will be saved, or both will fail.

That was easy enough, but now how do we retrieve the attachments? The list of attachments for a particular document is accessible via the session, as shown in <<get-attachment-names>>.

[[get-attachment-names]]
.Getting the list of attachments for a support call
[source,csharp]
----
using (var session = store.OpenSession())
{
	var call = session.Load<SupportCall>("SupportCalls/238-B");
	var attachments = session.Advanced.GetAttachmentNames(call);

	// render the call and the attachment names
}
----

Calling `GetAttachmentNames` is cheap; the attachments on a document are already present in the document metadata, which we loaded as part of
getting the document. There is no server-side call involved. Note that the result of `GetAttachmentNames` doesn't include the _content_ of the
attachments. To get the attachment itself and not just its name, you need to make an additional call, as shown in <<get-attachment-content>>.

[[get-attachment-content]]
.Getting an attachment content
[source,csharp]
----
using (var session = store.OpenSession())
{
	var call = session.Load<SupportCall>("SupportCalls/238-B");
	var attachments = session.Advanced.GetAttachmentNames(call);

	using (var stream = session.Advanced.GetAttachment(call, 
		attachments[0].Name))
	{
		// process the content of the attachment 
	}
}
----

Each call to `GetAttachment` will make a separate call to the server to fetch the attachment. If you have a lot of attachments, be aware that 
fetching all their information can be expensive due to the number of remote calls that are involved. 

=== Working with the document metadata

In the previous section, we noted that attachment information is stored in the document metadata. RavenDB uses the metadata for a 
lot of things. Most of them you don't generally care about (etag, change vector, etc.). But the document metadata is also available 
to you for your own needs and use.

An actual use case for direct use of the document metadata is pretty rare. If you want to store information, you'll typically want to
store it in the document itself, not throw it to the metadata sidelines. Typical use cases for storing data in the metadata are cross-cutting
concerns. The preeminent one is auditing. You may want to see who edited a document, for example.

In order to demonstrate working with the metadata, we'll consider creating a support call. Handling a support call can be a complex process 
that has to go through several steps. In this case, we will save the new support call document to RavenDB with a draft status in the metadata.
Typical modeling advice would be to model this explicitly in the domain (so you'll have an `IsDraft` or `Status` property on your model), 
but for this example, we'll use the metadata. You can see the code for setting a draft status in the metadata in <<set-metadata-draft-status>>.

[[set-metadata-draft-status]]
.Setting a metadata flag as part of creating a new support call
[source,csharp]
----
using (var session = store.OpenSession())
{
	var call = new SupportCall
	{
		Started = DateTime.UtcNow,
		Issue = customerIssue,
		CustomerId = customerId
	};
	session.Store(call);

	var metadata = session.Advanced.GetMetadataFor(call);
	metadata["Status"] = "Draft";

	session.SaveChanges();
}
----

We can call `GetMetadataFor` on any document that has been associated with the session. A document is associated with the session either by 
loading it from the server or by calling `Store`. After the document has been associated with the session, we can get its metadata and manipulate it.

Changes to the metadata count as changes to the document and will cause the document to be saved to the server when `SaveChanges` is called.

=== Cross cutting concerns with session events

The client API exposes a number of events that you can register to in order to deal with cross cutting concerns. Those events allow you to
effect the behavior of the RavenDB client API in a global fashion. 

The most commonly used events are list below (see the full listing in the online documentation):

* `OnBeforeStore` - called for each new or updated entity that we store to the server in `SaveChanges`, _before_ the server call.
* `OnAfterSaveChanges` - called for each entity that we send to the server in `SaveChanges`, _after_ the server replied back _successfully_.
* `OnBeforeDelete` - called from `SaveChanges` on any entity that was marked to be deleted.
* `OnSessionCreated` / `OnSessionDisposing` - allow to run your own logic on session creationg & disposal.
* `OnBeforeQuery` - called before sending a query to the server. Useful for logging or adding conditions to the query in a global fashion.
* `OnBeforeConversionToDocument` / `OnAfterConversionToDocument` and `OnBeforeConversionToEntity` / `OnAfterConversionToEntity` - allow to
   customize serialization and deserialization from JSON documents to your domain entities.

You can register to those events globally, at the `DocumentStore` level or at the individual session level. If you want to register to the
`DocumentStore`, you _must_ do so before you call `documentStore.Initialize()`. All sessions inherit their `DocumentStore` events (you 
can register more event handlers on the session as well, if needed).

<<audit-before-store>> shows how we can use the `OnBeforeStore` to add audit metadata to our documents.

[[audit-before-store]]
.Using `OnBeforeStore` to register the current user in modified documents metadata
[source,csharp]
----
using var store = new DocumentStore
{
    Urls = ["http://localhost:8080"],
    Database = "Northwind"
};
store.OnBeforeStore += (sender, e) =>
{
    e.DocumentMetadata["Modified-By"] = 
        System.Environment.UserName;
};
store.Initialize();
using (var session = store.OpenSession())
{
    session.Store(new Employee
    {
        FirstName = "John",
        LastName = "Doe",
    });
    session.SaveChanges();
}
----

The result of running the code in <<audit-before-store>> is shown in <<audit-metadata-output>>, where we show the resulting metadata on 
the server side.

[[audit-metadata-output]]
.The metadata of the employee document saved in <<audit-before-store>>, including the `Modified-By` audit field.
[source,json]
----
{
    "@metadata": {
        "@collection": "Employees",
        "Raven-Clr-Type": "Tryouts.Program+Employee, Tryouts",
        "Modified-By": "Oren Eini"  <1>
    }
}
----

Note that the `OnBeforeStore` and all the other events are _not_ async in nature. You can access the session using the provided
event args (`e.Session`), but you don't have access to the `Load<T>()` or `LoadAsync<T>()` easily. The session is harden to allow 
accessing the session (including loading other documents or modifying them) while inside the event, but it makes for a pretty 
complex system, from an architecture standpoint.

Another example of using those events is using `OnBeforeDelete` to validate the behavior of the system, as you can see in
<<validating-delete-employee>>.

[[validating-delete-employee]]
.Using `OnBeforeDelete` event to validate the business meaning of the operation
[source,csharp]
----
store.OnBeforeDelete += (sender, e) =>
{
    switch (e.Entity)
    {
        case Employee employee 
            when employee.EmploymentStatus == EmploymentStatus.Tenured:

            throw new InvalidOperationException(
                "Deletion Blocked: Employee is Tenured and " + 
                "cannot be removed without a formal revocation process."
            );
    }
};
----

<<validating-delete-employee>> checks if we are trying to delete a tenured employee, throwing an exception (and canceling) the
`SaveChanges()` if that is the case.

You can do a lot with those events, but you need to be aware that:

* These events run in the _client side_ - as such, a different client (or manual operation) will not execute those.
* It is easy to use these events for cross-cutting concerns, but it is also easy to miss their actions. If you make use of them
  be sure to properly document their effect on the system. I like making sure that if I have a before store event, I add _something_
  to the document metadata that makes it clear that it was modified by an event handler. The `Modified-By` metadata field is a good
  example of that.

=== Change tracking and `SaveChanges`

The document session implements change tracking on your documents, as you can see in <<save-changes-tracking>>.

[[save-changes-tracking]]
.Saving the changes to a document without manually tracking what changed
[source,csharp]
----
using (var session = store.OpenSession())
{
	var call = session.Load<SupportCall>("SupportCalls/238-B");
  
	call.Ended = DateTime.UtcNow;

	session.SaveChanges();
}
----

The session's change tracking (and identity map) means that you don't have to keep track of what changed and manually 
call `Store`. Instead, when you call `SaveChanges`, all your changes will be sent to the server in a single request.

You have a few knobs available to tweak the process. `session.Advanced.HasChanges` will let you know if calling `SaveChanges` 
will result in a call to the server. And `session.Advanced.HasChanged(entity)` will tell you when a particular `entity` has 
changed. You can also take it up a notch and ask RavenDB to tell you _what_ changed, using `session.Advanced.WhatChanged()`. 
This will give you all the changes that happened in the session. The `WhatChanged` feature can be nice if you want to highlight 
changes for user approval, for example, or if you just want to see what modifications were made to your model after a certain operation.

You can also tell RavenDB not to update a particular instance by calling `session.Advanced.IgnoreChangesFor(entity)`. 
The document will remain attached to the session and will be part of any identity map operations, but it won't be saved to the server when `SaveChanges` is called. Alternatively, you can call `session.Advanced.Evict(entity)` to make the session completely forget about a document.

These operations tend to be useful only in specific cases, but they are very powerful when utilized properly.

=== Optimistic concurrency

We covered optimistic concurrency in <<document-modeling>>, but only in the most general terms. Now, let's 
take a look and see how we can use optimistic concurrency in practice. <<concurrent-modifications-last-write-wins>> 
shows two simultaneous sessions modifying the same support call.

[[concurrent-modifications-last-write-wins]]
.Concurrent modifications of a support call
[source,csharp]
----
using (var sessionOne = store.OpenSession())                            <1>
using (var sessionTwo = store.OpenSession())
{
	var callOne = sessionOne.Load<SupportCall>("SupportCalls/238-B");   <2>
	var callTwo = sessionTwo.Load<SupportCall>("SupportCalls/238-B");
  
	callOne.Ended = DateTime.Today;                                     <3>
	callTwo.Ended = DateTime.Today.AddDays(1);
  
	sessionOne.SaveChanges();                                           <4>
	sessionTwo.SaveChanges();
}
----
<1> Opening two _distinct_ sessions.
<2> Loading the _same_ document on both sessions at once.
<3> Modify the two entities that represent the same in different sessions.
<4> Save the changes in both sessions, simulating concurrent work by two threads.

In the case of the code in <<concurrent-modifications-last-write-wins>>, we're always going to end up with the support call end date 
set to tomorrow. This is because, by default, RavenDB uses the `Last Write Wins` model. You can change that by setting 
`store.Conventions.UseOptimisticConcurrency` to "true," which will affect all sessions, or you can change it 
on a case-by-case basis by setting `session.Advanced.UseOptimisticConcurrency` to "true" on the session directly.

In either case, when this flag is set and `SaveChanges` is called, we'll send the modified documents to the server alongside their 
change vectors that were received from the server when loading the documents. This allows the server to reject any stale writes. If 
the flag were set to true, the code in <<concurrent-modifications-last-write-wins>> would result in a 
`ConcurrencyException` on the `sessionTwo.SaveChanges()` call.

This ensures that you can't overwrite changes you didn't see, and if you set `UseOptimisticConcurrency`, you need to handle this 
error in some manner.

==== Pessimistic locking

When changes happen behind our backs to the document we modified, optimistic locking handles it. Pessimistic locking, on the other hand, 
prevents those changes entirely. RavenDB does _not_ support pessimistic locking. And while you really need support from the database 
engine to properly implement pessimistic locking, we fake it in an interesting way. The following is a recipe for using
approximating pessimistic locking in RavenDB.  We mention it not so much because it's a good idea, but because it allows us to explore several 
different features and see how they work together.

Using pessimistic locking, we can lock a document for modification until we release the lock or until a certain amount of time has gone by. We 
can build a pessimistic lock in RavenDB by utilizing the document metadata and optimistic concurrency. It's easier to explain with code, 
and you can find the `Lock` implementations in <<pessimistic-lock-extension>>.footnote:[This is _not_ a recommended way to do this, there
are a lot of problems with using this approach, see later in this section for a much better alternative.]

[[pessimistic-lock-extension]]
.Extension method to add (pretty bad) pessimistic locking to the session
[source,csharp]
----
public static IDisposable Lock(
	this IDocumentSession session, 
	string docToLock)
{
  var doc = session.Load<object>(docToLock);                        <1>
  if (doc == null)
	  throw new DocumentDoesNotExistException("The document " + 
		  docToLock + " does not exists and cannot be locked");

  var metadata = session.Advanced.GetMetadataFor(doc);              <2>
  if (metadata.GetBoolean("Pessimistic-Locked"))                    <3>
  {
	  // the document is locked and the lock is still value
	  var ticks = metadata.GetNumber("Pessimistic-Lock-Timeout");   <4>
	  var lockedUntil = new DateTime(ticks);
	  if (DateTime.UtcNow <= lockedUntil)                           <5>
		  throw new ConcurrencyException("Document " + 
			  docToLock + " is locked using pessimistic locking");
  }
  
  metadata["Pessimistic-Locked"] = true;                            <6>
  metadata["Pessimistic-Lock-Timeout"] = 
	  DateTime.UtcNow.AddSeconds(15).Ticks;
  
  // will throw if someone else took the look in the meantime
  session.Advanced.UseOptimisticConcurrency = true;
  session.SaveChanges();                                            <7>

  return new DisposableAction(() =>
  {
	  metadata.Remove("Pessimistic-Locked");
	  metadata.Remove("Pessimistic-Lock-Timeout");
	  Debug.Assert(session.Advanced.UseOptimisticConcurrency);      <8>
	  session.SaveChanges();
  });
}
----
<1> Load the document to lock from the session
<2> Get the document data, which contains the pessimistic lock details
<3> Check if this document was pessimistically locked.
<4> Get the expiration value of the lock.
<5> Check if the lock is still valid and throw if that is still the case.
<6> Update the document metadata to reflect its locked statuc.
<7> Save the metadata changes after making sure that the session enabled optimistic concurrency.
<8> Remove the pessimistic locking metadata and save the session again, with optimistic concurrency.

There's quite a bit of code in <<pessimistic-lock-extension>>, but there isn't actually a lot that gets done. We load a document and check if 
its metadata says it is locked using `Pessimistic-Locked` and `Pessimistic-Lock-Timeout`. The key is that we rely on optimistic concurrency to
ensure that our locking mechanism is safe in the face of concucrency. If anyone else is trying to `Lock` the document at the same time, we are
ensured that only a single session will be successfull, and all other contenders will fail.

The `Lock` method returns an `IDisposable` instance that handles releasing the lock. This is done by removing the metadata values and then 
calling `SaveChanges` again. If the lock has timed out and someone took the lock, we'll fail here with a concurrency exception as well.

.Avoid your own distributed pessimistic locks
****
There's a reason why RavenDB does not include a pessimistic lock feature, and I strongly recommend you avoid using the recipe above. 
It's here to show how you'd use several different features at once to achieve a goal.

Actually handling a distributed lock is a non-trivial issue. Consider a RavenDB cluster with multiple nodes. If two lock requests go to two
distinct nodes at the same time, _both_ of them will succeed. The two nodes will quickly discover the conflicting updates and generate 
a conflict. But it isn't guaranteed they'll discover it inside the lock/unlock period.
 
Another issue is the subject of timing. If two clients have enough of a clock skew, a client might consider a lock to have expired even though 
it's still valid. Proper distributed locking requires a consensus protocol of some kind, and those aren't trivial to build or use. RavenDB does 
have a consensus protocol, but pessimistic locking is usually a bad fit for an OLTP environment, and we decided not to implement it.
****

A typical use for pessimistic locks is to lock a document while a user is editing it. That might sound like a good idea, but experience has 
shown that, in most cases, it leads to trouble. Consider, for example, version control systems (such as Git or Subversion). 
If you're reading this book, you've likely used a source control of some kind. If you haven't, I suggest you pick up a book about 
source control and prioritize it over this one: learning about that is far more foundational.

Early source control systems (SourceSafe is a good example) used locks as their concurrency model, and that led to a lot of problems. Say Joe
locks a file and then leaves on vacation. All of his coworkers then have to wait until he gets back before committing code to that  file. This
is a typical problem that arises in such cases. The same happens when you have pessimistic locks. Implementing pessimistic locks requires you to
also implement forced lock release, a feature that tells you who locked the document and a whole slew of management functions around it.
Typically, implementing optimistic concurrency or merging is easier and matches most users' expectations.

Having said that, a _proper_ way to build a pessimistic lock in RavenDB relies on using the Compare Exchnage feature we covered briefly in
<<zero-to-ravendb>>. As a reminder, RavenDB's Compare Exchange allow you to essentially implement `Interlocked.CompareExchange()` in a 
distributed environment. You can see the code for this in <<pessimistic-concurrency-cmp-xng>>.

[[pessimistic-concurrency-cmp-xng]]
.Implementing a distributed pessimistic lock in RavenDB using the compare exchange feature
[source,csharp]
----
async Task<IAsyncDisposable> LockAsync(
    IDocumentStore store, 
    string key, 
    string owner, 
    TimeSpan timeout)
{
    using var session = store.OpenAsyncSession(new SessionOptions   <1>
    {
        TransactionMode = TransactionMode.ClusterWide
    });
    CompareExchangeValue<string> value = session.Advanced
        .ClusterTransaction.CreateCompareExchangeValue(key, owner); <2>
    value.Metadata["@expires"] = 
        DateTime.UtcNow.Add(timeout).ToString("o);                  <3>
    
    await session.SaveChangesAsync();                               <4>

    return new DisposableAsyncAction(async () =>                    <5>
    {
        using var disposeSession = store.OpenAsyncSession(new SessionOptions
        {
            TransactionMode = TransactionMode.ClusterWide           <6>
        });
        
        disposeSession.Advanced.ClusterTransaction
            .DeleteCompareExchangeValue(key, value.Index);          <7>
        
        await disposeSession.SaveChangesAsync();                    <8>
    });
}
----
<1> Open a cluster-wide session (to ensure consistency in a distributed cluster).
<2> Creates the compare exchange value using the specified `key` (ensuring that it is new). We don't care
    about the value in this case, so we register the `owner` of the key here, for debugging purposes.
<3> Telling RavenDB that it should expire this value (RavenDB handles this part automatically).
<4> Save the changes (and get a `ConcurrencyException` if the `key` already exists).
<5> The unlocking part of the process, to allow using `await using(Lock(...)) { ... }` to handle cleanup.
<6> Creating a second cluster-wide session, to handle the deletion of the compare exchange value.
<7> Delete the compare exchange value, using the previously defined `value.Index` to ensure consistency of the operation.
<8> Saving the changes (or getting `ConcurrencyException` if the `key` was already removed or changed).

<<pessimistic-concurrency-cmp-xng>> is relying on the nature of the compare exchange feature in RavenDB, to allow us to 
have an atomic operation in a distributed cluster. We also use the `@expires` option to let RavenDB handle the cleanup
and expiry of the lock on its own. We'll discuss this feature in more detail later.

The sort of pessimistic lock that is shown in <<pessimistic-concurrency-cmp-xng>> is a cooperative one. All users must
call to the `Lock` method to ensure proper synchronization. It doesn't rely on an existing connection to be kept alive
and will be cleaned up solely based on expiration time. That means that you can also use that in an _offline_ manner.
We talk a bit about that in the next section.

===== Offline optimistic concurrency

We looked at online optimistic concurrency in <<concurrent-modifications-last-write-wins>>, where we loaded a document 
into the session, modified it and then saved. In that time frame, if there was a change, we'd get a concurrency exception.
But most software doesn't work like that. In a web application, you aren't going to keep the document session open for 
as long as the user is on the site. Instead, most likely you'll use a session-per-request model. The user will load a page 
with the document's content in one request and modify it in another request. There isn't a shared session in sight, so how 
can we implement optimistic concurrency?

All you need to do is send the change vector of the document to the user and accept it back when the user wants to save 
the document. <<offline-optimistic-concurrency>> shows an example using two separate sessions with concurrency handling between them.

[[offline-optimistic-concurrency]]
.Concurrent modifications of a support call (offline optimistic concurrency)
[source,csharp]
----
string changeVector;
Supportcall callOne;

using (var sessionOne = store.OpenSession())                        <1>
{
	callOne = sessionOne.Load<SupportCall>("SupportCalls/238-B");
	changeVector = sessionOne.Advanced.GetChangeVectorFor(callOne);
}

using (var sessionTwo = store.OpenSession())                        <2>
{
	var callTwo = sessionTwo.Load<SupportCall>("SupportCalls/238-B");
	callTwo.Ended = DateTime.Today.AddDays(1);
	sessionTwo.SaveChanges();
}

callOne.Ended = DateTime.Today;                                     <3>

using (var sessionThree = store.OpenSession())                      
{
	sessionThree.Advanced.UseOptimisticConcurrency = true;          
	sessionThree.Store(callOne, changeVector, callOne.Id);          <4>
	sessionThree.SaveChanges(); // will raise ConcurrencyException  <5>
}
----
<1> Load the document and record its current change vector in one session.
<2> In another session, load and modify the document. 
<3> Modify the first version we loaded, simulating changing the entity by the user.
<4> Associating the _new_ session (with optimistic concurrency) with the _original_ version of the document, with the original change vector.
<5> Saving the changes in the session (and getting a `ConcurrencyException` because it was already changed)

The code in <<offline-optimistic-concurrency>> simulates how we open a session to load a document and send it to the client. Then update it
in a separate session when we get the reply from the client. Interleaved with that, we have another session that modified the same docuemnt.
We provide the _original_ change vector to the final session, ensuring that we can detect any changes behind our back.

Calling `Store()` with the original change vector gives the RavenDB client API enough information for us to do an optimistic concurrency
check from the time we loaded `callOne` in the first session. In a web scenario, you'll typically send the change vector alongside the actual 
data and get it back from the client to do the check. You might also want to check out the `Changes API`, which is covered a little later in 
this chapter. This might help you get early change notifications when you need to implement offline optimistic concurrency.

=== Patching documents and concurrent modifications

The typical workflow with RavenDB is to open a session, load a document, run some business logic and call `SaveChanges`. When 
you follow those steps, the session will figure out what documents have changed and send them to the server. This model is simple 
and easy to follow, and it's the recommended way to work.

However, there are a few scenarios in which we don't want to send the entire document back to the server. For example, if our 
document is very large and we want to make a small change, we can avoid that cost. Another reason to avoid the full document 
save is a scenario that calls for concurrent work on a document.

Let's consider the `SupportCall.Votes` property. Two users may very well want to vote on the same support call at the same time. 
One way to handle that is to load the support call, increment the `Votes` property and call `SaveChanges`. In order to handle 
concurrent modifications, we can utilize optimistic concurrency and retries. But that's quite a lot of work to write, and if the 
document is large, there's also a lot of data going back and forth over the network for little reason. <<patch-increment-votes>> 
shows how we can do much better.

[[patch-increment-votes]]
.Incrementing a property using the Patch API
[source,csharp]
----
using (var session = store.OpenSession())
{
	session.Advanced.Increment<SupportCall, int>(
            "SupportCalls/238-B", 
            c => c.Votes, 
            1);

	session.SaveChanges();
}
----

What the code in <<patch-increment-votes>> does is generate a patch request, rather than load and save the full document. 
That request is stored in the session, and when `SaveChanges` is called, it will be sent to the server (alongside any other 
changes/operations made on the session, as usual). On the server side, we'll apply this operation to the document. This patch 
request is safe to call concurrently, since there's no loss of data when executing patches.

.Which is faster, patching or load/save?
****
The hasty answer is that patching is faster. We send a lot less data, and we need one less round trip to do so. Winning all around, right?

But the real answer is that things are bit more complex. The patch request is actually a JavaScript function that we send. That means 
we need to parse and run it on the server side, potentially marshal values into the script environment and then marshal it back. 
Conversely, the code path for loading and saving documents in RavenDB is well trodden and has been optimized plenty. That means in many 
cases it might be easier to just load and modify the document directly, rather than use a patch.

Patching _isn't_ expensive; I want to emphasize that. But at the same time, I've seen codebases where _all_ writes had to be made 
using patching because of perceived performance benefits. That resulted in an extremely hard-to-understand system that was resistant 
to change. The general recommendation is to utilize patching only when you need to support concurrent modifications.

Note that in most cases concurrent modifications of the same document is _not_ the default. A properly modeled document should have 
a single reason to change,  but it's common that documents have additional data on them (like the `Votes` property or `Comments`) that are 
important to save but don't have any real business logic attached to them.

That kind of change is fine to do using patching. If you find yourself trying to run serious business logic in patch scripts (we'll 
see exactly how to do this in a bit), you should move that into your own business logic. For a numerical value like `Votes`, the _proper_
answer in RavenDB is to use counters, not a document property and patching.

An important consideration to take into account is that there is no guarantee as to the order in which the patches will run. But, 
you don't need to worry about concurrency between patches on the same document as there is no concurrent/interleaved execution of 
the scripts on the same document.  
****

A slightly more complex example of the use of patching is adding a comment to a `SupportCall`. Just like before, we want to support adding a 
comment concurrently. But to make things a bit more interesting, we'll add a business rule: a call that has been ended cannot have additional 
comments added to it. <<add-comment-using-patch>> shows the obvious way to accomplish this.

[[add-comment-using-patch]]
.Adding a comment to a support call using patch
[source,csharp]
----
using (var session = store.OpenSession())
{
	var call = session.Load<SupportCall>("SupportCalls/238-B");
	if (call.Ended != null)
		throw new InvalidOperationException("Cannot comment on closed call");

	session.Advanced.Patch(call, c => c.Comments, 
		comments => comments.Add("This is important stuff!"));

	session.SaveChanges();
}
----

In <<add-comment-using-patch>>, you can see how we moved from using the simple `Increment` call to the `Patch`, which allows us to 
either replace a property value completely or add an item to a collection. If you look closely at the code in <<add-comment-using-patch>>,
you'll find that there's a hidden race condition there. The business rule is that we can't add comments to a closed call; we're able to 
load the call, check that its `Ended` property is null and then send the patch request to the server. However, in the meantime, 
another client could have closed the call, and yet we'd still add the comment.

The seriousness of this issue depends entirely on the domain and the model. It's possible that you _do_ want to add comments during 
that period, or it's possible that allowing it could break important business invariants. 

.Patch requests are sent as part of `SaveChanges`
****
It's probably obvious, but I wanted to spell this out explicitly. Calls to `Patch`, `Increment` or `Defer` don't go to the 
server immediately. Instead, they're added to the list of operations the session needs to execute and will be sent to the 
server in a single batch (along with any modified documents) when `SaveChanges` is called. 
If you have multiple patch operations in the same session on the same document, they'll be merged into a single patch. And if there
are multiple patches on different documents, they'll all be executed within the same transaction, as a single unit.
****

There are two ways to avoid the race condition. We can send a change vector to the server asking it to fail with a concurrency 
exception if the document has been modified since we last saw it. That _works_, but it defeats the whole point of using patches 
for concurrent modification of the document. The second alternative is to move the invariant check into the script itself. 
Calls to `Increment` and `Patch` are actually just wrappers around the `Defer` call, which allows you to add work to the session 
that's to be sent to the server when `SaveChanges` is called.

In <<patch-script-maintain-invariants>>, we're dropping down to using `Defer` directly to manipulate the patch request ourselves, 
with no wrappers. As you can see, this is a bit involved, but overall it's pretty straightforward.

[[patch-script-maintain-invariants]]
.Using a patch script to maintain call invariants
[source,csharp]
----
using (var session = store.OpenSession())
{
	session.Advanced.Defer(new PatchCommandData(
		id: "SupportCalls/238-B",
		changeVector: null, 
		patch: new PatchRequest
		{
			Script = @"
				if (this.Ended != null)
					throw 'Cannot add a comment to a closed call';
				this.Comments.push($comment);
				",
			Values =
			{
				["comment"] = "This is important stuff!!"
			} 
		},
	patchIfMissing: null));
  
	session.SaveChanges();
}
----

The code in <<patch-script-maintain-invariants>> passes a `PatchCommandData`, containing the relevant document ID, 
to `Defer`. The key part is in the `PatchRequest` itself. We do the check on the document and fail if the call has already 
been closed. If it hasn't, we add the comment to the call. You can also see that we don't have to deal with string
concatenation here since we can pass arguments to the scripts directly. There's also the option to run a script 
if the document does not exist (using `patchIfMissing`). This gives you the option to do a "modify or create" style of operation.

Using this method, we can be sure that we'll never violate the rule about adding comments to a closed call. A cautionary word, 
though: this is more complex than anything we've dealt with before, and I would only recommend doing it if you really must. 

=== Deferring commands

In the previous section, we used the `Defer` method to register a `PatchCommandData` on the session, to be executed when 
`SaveChanges` is called. But `Defer` is more generic then this. It's a general mechanism for the user to register arbitrary 
commands that will be part of the same transaction as the `SaveChanges`.

.The RavenDB API is like an ogre. It has layers
****
Like the popular character Shrek, RavenDB API is composed of layers. At the top, you have the document store and the document session. 
Those are built using the operations concept, which you typically won't use directly. The operations are handled via the request executor,
which allows you to generate requests directly to the server (and take advantage of RavenDB's authentication and automatic failover).

The case of `Defer` is a good example. Instead of forcing you to drop down all the way, we expose an extension point in the session so you can plug in a command of your own and piggyback on the session handling of transactions.
****

The available commands range from putting and deleting documents and attachments to applying patches that delete documents having some 
prefix. Aside from the patch operation, the rest are only useful in rare cases. The most common use of `Defer` beyond patch is when you 
need fine-grained control over the operations that will be executed in a single transaction, to the point where you want to control 
the ordering of the operations.

RavenDB doesn't allow changing the document's collection by updating the `@collection` metadata. If you need to move a document to a different 
collection you must delete the old document and then create a new one with the appropriate collection. The session doesn't allow you to both 
delete and modify a document in the same high-level operation. For the purpose of discussion, let's assume we _have_ to do this in a single 
transaction so no other client sees a transient deleted state.

To be clear, this is a strange situation, dreamt up specifically to showcase a feature that should be used only in special circumstances. This 
escape hatch in the API exists to prevent you from being blocked if you need something we didn't foresee, but it is probably a bad idea to make 
it the front door.

Another reason to avoid using `Defer` is that it's lower in the RavenDB client API layers. Instead of dealing with high level concepts like 
entities, you'll be dealing with the direct representation RavenDB uses for JSON (the blittable format, discussed later). That format is 
optimized for performance; developer convenience was secondary in its design.

=== Bulk inserting documents to RavenDB

RavenDB is fast, _really_ fast, but it still needs to face operational realities. The 
https://en.wikipedia.org/wiki/Fallacies_of_distributed_computing[fallacies of distributed computing] still apply, 
and I/O takes a non-trivial amount of time. This means that when you want to get the best speed out of RavenDB, you need to 
help it achieve that.

.Stacking the deck
****
I'm going to be talking performance numbers in this section, and I wanted to make it clear that I've intentionally chosen 
the worst possible situation for RavenDB and then compounded the issue by using the wrong approaches. This is so I can show 
the real costs in a manner that's highly visible.

I'll refer you again to the [fallacies of distributed computing](https://en.wikipedia.org/wiki/Fallacies_of_distributed_computing). 
I'm trying to select a scenario that would break as many of those fallacies as possible and show how RavenDB is able to handle them. 
****

<<write-10000-documents-sequential>> shows the absolute slowest way to write 10,000 documents into RavenDB.

[[write-10000-documents-sequential]]
.Writing 10,000 documents, one at a time
[source,csharp]
----
var sp = Stopwatch.StartNew();
for (int i = 0; i < 10_000; i++)
{
	using (var session = store.OpenSession())
	{
		session.Store(new Customer
		{
			Name = "Customer #" + i
		});
		session.SaveChanges();
	}
}
Console.WriteLine(sp.Elapsed);
----

For fun, I decided to run the code in <<write-10000-documents-sequential>> against the live test instance we have. 
That instance was in San Francisco, and I was testing this from Israel. The test instance was also running as a container 
inside an AWS `t2.medium` machine (two cores and 4 GB of memory, with burst-only mode). In other words, this
performance test was heavily biased against RavenDB, and the results were not great. In fact, they were _bad_.

This is because we're running each write as an independent operation, and we have to wait for the previous operation
to complete before we can start the new one. What's more, the database server handles just a single request concurrently, 
which means we have no way to amortize I/O costs across multiple requests. This is the absolute worst way you can write a 
large amount of documents into RavenDB because most of the time is spent just going back and forth
between the client and the application. For each request, we have to make another REST call, send a packet to the server, etc.
On the other side, the server accepts a new request, processes it and commits it to disk. During the entire process, it's 
effectively idle, since most of the time is spent waiting for I/O. That's a big waste all around.

Each request took about 220–260 milliseconds to run. Writing the first 1,000 documents took four minutes and six seconds, 
and 2,000 requests took eight minutes on the dot. The full 10,000 documents would take 40 minutes or so. Granted, we're intentionally 
going to a remote server, but still...

What happens when we're running the writes in parallel? The code in <<write-10000-parallel>> shows how to do this.

[[write-10000-parallel]]
.Writing 10,000 documents, with a bit of parallelism thrown in
[source,csharp]
----
var sp = Stopwatch.StartNew();
Parallel.For(0, 10_000, i =>                    <1>
{
	using (var session = store.OpenSession())
	{
		session.Store(new Customer
		{
			Name = "Customer #" + i
		});
		session.SaveChanges();
	}
});
Console.WriteLine(sp.Elapsed);
----
<1> Using `Parallel.For()` to execute the inner lambda 10,000 times in parallel in the thread pool.

Using the method in <<write-10000-parallel>>, I was able to write 1,000 documents in 56 seconds. We got to 2,000 in a minute and a half,
3,000 in a minute and 50 seconds, etc. The reason for the speed up is actually related to how thread pooling is handled on the client side. 
Since we make a lot of blocking requests, the thread pool figures out that we have plenty of blocking work and creates more threads. 
That means we have the chance to do more concurrent work. So as time goes by, more threads are created and we make additional concurrent 
requests to RavenDB. 

The total time of writing 10,000 documents in this setup was two minutes and 52 seconds. So we've gotten done 20 times faster than we did using 
sequential writes. The code in <<write-10000-parallel>> is still using synchronous calls, which means the client side is spinning threads to 
handle the load and we're limited by the rate of new thread creation on the client. 

RavenDB also supports an async API, which is much more suitable for scale-out scenarios because we aren't holding a thread for the duration of 
the connection. <<write-10000-async>> shows how we can write all those documents in parallel,  using the async API. The code is a tad complex 
because we want to control the number of concurrent requests we make. Spinning 10,000 concurrent requests will likely load the network and 
require careful attention to how they are managed, which is out of scope for this book. Instead, I limited the number of concurrent 
connections to 128.

[[write-10000-async]]
.Writing 10,000 documents, using async API
[source,csharp]
----
var sp = Stopwatch.StartNew();
var semaphore = new SemaphoreSlim(128);             <1>

async Task WriteDocument(int i)                     <2>
{
	using (var session = store.OpenAsyncSession())
	{
		await session.StoreAsync(new Customer
		{
			Name = "Customer #" + i
		});
		await session.SaveChangesAsync();
	}
	semaphore.Release();                            <3>
}

var tasks = new List<Task>();
for (int i = 0; i < 10_000; i++)                    <4>
{
	semaphore.Wait();
	tasks.Add(WriteDocument(i));
}

Task.WaitAll(tasks.ToArray());

Console.WriteLine(sp.Elapsed);
----
<1> Semaphore set to 128 to limit maximum concurrency.
<2> The actual individual `async` store operation to the database.
<4> Releasing the semaphore when we are done saving the document.
<3> Loop 10,000 times to execute the `WriteDocument`, but limiting to the 128 concurrent tasks.


The code in <<write-10000-async>> writes 1,000 documents in just under 10 seconds, and it completes the full 10,000 writes in 
under 30 seconds (29.6, on my machine). The speed difference is, again, related to the client learning our pattern of behavior 
and adjusting itself accordingly (creating enough buffers, threads and other resources needed; warming up the TCP connections.footnote:[
TCP slow start can be a killer on benchmarks.]).

However, we really had to make an effort. We wrote explicit async code and managed it, rate-limited our behavior and jumped through several 
hoops to get a more reasonable level of performance. Note that we went from over 40 minutes to less than 30 seconds in the span of a 
few pages. Also note that we haven't actually modified _what_ we're doing. We only changed how we're talking to the server,
but it had a huge impact on performance.

You can take it as a given that RavenDB is able to process as much data as you can feed it. The typical concern in handling writes is how fast 
we can get the data to the server, not how fast the server can handle it. 

RavenDB contains a dedicated API and behavior that makes it easier to deal with bulk loading scenarios. The bulk insert API uses a single 
connection to talk to the server and is able to make much better use of the network. The entire process is carefully orchestrated by both the 
client and the server to optimize performance. Let's look at the code in <<bulk-insert-100000>> first and then discuss the details.

[[bulk-insert-100000]]
.using bulk insert to write 100,000 documents, quickly
[source,csharp]
----
var sp = Stopwatch.StartNew();

using (var bulkInsert = store.BulkInsert())
{
	for (int i = 0; i < 100_000; i++)
	{
		bulkInsert.Store(new Customer
		{
			Name = "Customer #" + i
		});
	}
}

Console.WriteLine(sp.Elapsed);
----


The code in <<bulk-insert-100000>> took two minutes and 10 seconds to run on my machine. 
Which is interesting, because it seems slower than the async API usage sample, right?
Except there's one problem. I made a typo when writing the code and wrote a _hundred_ thousand documents instead of _ten_ thousand. 
If I was writing merely 10,000 documents, it would complete in about 18 seconds. The code is fairly trivial to write, similar to our first 
sample in Listing 4.14, but the performance is many times faster.

To compare the costs, I ran the same code against a local machine, giving me a total time of 11 seconds to insert 
100,000 documents (instead of two minutes remotely). If we wanted to compare apples with apples, then the cost for writing 
10,000 documents is shown in <<bulk-insert-comparison>>.

[[bulk-insert-comparison]]
.Bulk insert costs locally and remotely
[cols="1,1,1",options="header"]
|===
|                |   Remote    |    Local    

| Session        | 41 *minutes*| 20 seconds  
| Bulk Insert    | 18 seconds  | 6.5 seconds 
|===

You can see that while bulk insert is significantly faster in all cases, being over three times faster than the session option 
(<<write-10000-documents-sequential>>) locally seems insignificant considering it's over 130 times faster in the remote case. 
The major difference, as you can imagine, is the cost of going over the network, but even on the local machine (and we're not 
even talking about the local network), there's a significant performance benefit for bulk insert.

Amusingly enough, using bulk insert still doesn't saturate the server. For large datasets, it's advisable to have parallel bulk insert 
operations going at the same time. This gives the server more work to do, and it allows us to do optimizations that increase the ingest 
rate of the server.

The way bulk insert works is by opening a single long running request to the server and writing the raw data directly into the database. That 
means we don't need to go back and forth between the client and the server and can rely on a single network roundtrip to do all the work. The 
server, for its part, will read the data from the network and write it to disk when it's best to do so. In other words, bulk inserts 
are _not_ transactional. A bulk insert is actually composed of many smaller transactions, whose size and scope are determined by the 
server based on its own calculations, in order to maximize performance.

When the bulk insert is completed, you can rest assured that all the data has been safely committed to disk properly. But during the process, 
the data is committed incrementally instead of going with a single big-bang approach.

For the most part, RavenDB performance is ruled by how many requests you can send it. The more requests, the higher the degree of parallelism 
and the more efficiently  RavenDB can work. In our internal tests, we routinely bumped into hardware limits (the network card 
cannot process packets any faster, the disk I/O is saturated, etc.), not software ones. 

### Reading documents

We just spent a lot of time learning how we can write documents to RavenDB in all sorts of interesting ways. But for reading, 
how much is there really to know? We already learned how to load and query a document; we covered that in <<zero-to-ravendb>>.
We also covered `Include` and how to use it to effortlessly get referenced documents from the server. What else is there to talk 
about? As it turns out, quite a bit. 

In most applications, reads are far more numerous than writes, often by an order of magnitude. That means RavenDB needs to be 
prepared to handle a _lot_ of reads, and those applications typically have a number of ways in which they access, shape and 
consume the data. RavenDB needs to be able to provide an answer to all those needs.

The first feature I want to present allows you to dramatically increase your overall performance by being a little lazy.

