[[sharding-in-ravendb]]
## Sharding in RavenDB

We spent the previous couple of chapters exploring the distributed nature of RavenDB. Seeing how
RavenDB cluster operates and how RavenDB replicates data among the different nodes in the cluster.
Now is the time to discuss another layer of RavenDB's distributed behavior, sharding of data.

We talked about databases that span multiple nodes. Such usage is meant for high availability
scenarios, allowing you to have multiple copies of the data in case a node goes down. RavenDB manages
the distribution of such databases automatically for you. Data replication also allows for load
distribution using the `read behavior` option. However, this isn't suitable if the amount of data that
you have to store exceeds the amount that can reasonably be held in a single node.

With RavenDB replication, all the nodes in the database group will hold full copies of the data. This
is a great strategy that has a surprisingly long breathing room. The general recommendation is to start
looking at sharding when your data size is expected to be measured in multiple terabytes.
We have had multiple case studies of users running replicated databases in the greater than 5 TB range with no issue,
for example. Those do tend to be in the upper end of database size, though.

Sharding, on the other hand, allows you to split the data you have between the different nodes in the
cluster. For example, let's assume that we have 100 user documents in our system. With replication,
we'll have three nodes (`A`, `B`, `C`) and each one of them will have 100 documents. With sharding, we'll split them
evenly between the nodes, so node `A` will have 34 documents and nodes `B` and `C` will have 33 documents each.

Sharding is actually orthogonal to replication. You'll usually have both of them at the same time. Let's look
at <<shard-replication-table>>, for an example of how a typical topology might look.

[[shard-replication-table]]
.Distributing 100 users among 4 nodes and 3 shards
[cols="1,2,2,2,2",options="header"]
|===
|    | A        | B        | C        | D

| $0 | 34 Users | 34 Users |          |
| $1 |          | 33 Users | 33 Users |
| $2 | 33 Users |          |          | 33 Users
|===

In <<shard-replication-table>> you can see that we have four nodes (`A`, `B`, `C`, `D`) and three shards (`$0`, `$1`, `$2`). Each of the
shards contains some of the data and there are multiple copies of each shard's data. The reason we first covered
replication in this book is simple: sharding is actually layered on top of replicating databases.


### How sharding works in RavenDB

Sharding allows us to have a unified view of data that has been partitioned (sharded) to multiple nodes. A sharded
database is managed by RavenDB and appears to the outside world as if it was a (fairly large) single database. From
a client perspective, there is (almost) no change when working with a sharded database or an unsharded one.

As usual, it is easier to explain with a real world example. Let's consider a database for an ordering system, that
holds documents such as `Customers` and `Orders`. We'll create a sharded database called `Orders`.

// TODO: exact steps on how to do that

.Sharding terminology
****
To properly understand the rest of this chapter, I want to clarify my intent when I'm using the following terms:

* *Sharded database* -- a virtual database that looks to the outside world as if it was a normal RavenDB database and
  whose data is partitioned to multiple nodes in the cluster.
* *Shard (or Shard Id)* -- the _logical_ association of a document to a particular location. A sharded database is
  composed of 1,048,576 shards. Many shards can reside in a single node.
* *Fragment* -- the _physical_ database that holds some of the documents in a sharded database. A fragment holds all
  the shards (and the documents contained in them) associated with it. A fragment is a database that may be replicated
  to multiple nodes.
****

The `Orders` database has three fragments, with the following shard range allocation:

* `Orders$0` -- shards `0` - `349525`.
* `Orders$1` -- shards `349525` - `699050`.
* `Orders$2` -- shards `699050` - `1048576`.

Note that the `$<num>` notation is how RavenDB names the fragments. In our case, node `A` will house
`Orders$0` and `Orders$2`, while node `B` will host `Orders$0` and `Orders$1`, etc. (The exact allocation depends on the
cluster topology and the replication factor.)

Operations such as reads, writes or queries on the sharded `Orders` database will work normally as far as the client
is concerned. On the server side, RavenDB will direct the operations to the right fragment for the documents in
question. You can control the number of fragments and the shard allocations on database creation and during routine
operations.

RavenDB handles the allocation of documents to shards by hashing the document id. For instance, here are a few examples
of document ids and shard assignments:

* `orders/1-A` -- `151326`
* `customers/1-A` -- `982173`
* `orders/2-A$customers/1-A` -- `982173`

As you can see, `orders/1-A` is going to reside in fragment 0 (`Orders$0`). This is because its shard id is `151326`
and that range falls into `Orders$0`. On the other hand, both `customers/1-A` and `orders/2-A$customers/1-A` are
placed in `Orders$2`. This is not an accident. RavenDB allows you to specify the sharding namespace for a document by
using the `$` suffix; we'll touch on why this is important later in this chapter.

.The almighty $
****
RavenDB gives a special meaning to the `$` character in a sharded context. Database fragments are denoted with a
`$0` suffix to denote their number in the sharded database. Document ids with `$` in them are treated in a special
manner and allow you to control what shard a document will reside on.

Saving a document with just the `$` suffix (such as `orders/3-A$`) will cause RavenDB to invoke the specified content
based sharding function and assign it to the relevant shard. We'll discuss content based sharding later in
this chapter.
****

A query for documents on a sharded database will be routed to the relevant fragments automatically, and the results
aggregated from the various fragments automatically. Each fragment is effectively an independent database, which can
have its own replication factor and topology. This allows you to define a sharded database with replicas and
enjoy the usual benefits of RavenDB's high availability, etc.

Unlike an unsharded database, which can only be accessed from the nodes it resides on, a sharded database is accessible
from all nodes, including nodes that hold no fragments for this database. RavenDB will handle the routing of queries
and operations as needed.


### Using document ids for sharding

RavenDB uses the document id to decide what shard a particular document should reside on. This is computed using a
hash of the document id. The hash algorithm is: `xxhash64( docId.ToLower() ) % (1024 * 1024)`. This
method gives us good distribution of the data between the shards, which is critical for the success of a sharded
system.

RavenDB uses 1,048,576 fixed shards. This amount was chosen so that with a uniform distribution of data between the shards,
we'll have roughly 1 MB of data per shard for each terabyte of data in the sharded database. This results in shards
that are small enough to be moved relatively quickly if needed. Indeed, RavenDB will automatically balance the utilized
space between the fragments by moving shards between fragments as needed. You can also define the shard allocation
map manually.

.Beware of the obese shard
****
Placing documents in the same shard can be extremely useful for ensuring locality, but you also need to take
into account the behavior of the system as a whole. Because RavenDB can't break up a shard into individual pieces,
it is unable to respond to a scenario where a shard grows too large.

For example, in the `Orders` and `Customers` scenario, we have sharded the database according to the customer id.
Each `Order` will reside in the same shard as its `Customer`. This works great if the number of orders per
customer is up to a certain limit. But if we have customers that may have hundreds or thousands of orders, that creates very
large shards that RavenDB is not going to be able to break up.

In the context of the `Orders` database, it is unlikely to be too severe of a problem. At worst, we'll end up with a
single fragment holding a single (very large) shard and all the other fragments hosting all the other shards in
the system.

In other systems, however, that can be a major issue. If you are sharding based on geographical location and the
majority of your users are in New York City, you are going to end up with one very large and hot shard, with no
way to split the load among the various nodes.

By default, RavenDB will assign documents to shards on a fair basis, so you generally don't need to think about this
unless you define your own sharding policy. We'll discuss this in more detail later in this chapter.
****

In a distributed database, locality matters, a _lot_. When you shard your data, you are explicitly partitioning it. But
while you might want to partition the overall data set, you still want to maintain locality for related documents.
For example, if two documents strongly relate to one another, operations that touch both of them will be more
efficient if they reside on the same shard.

The actual behavior is a bit more nuanced, however. Let's consider the following documents:
`customers/6-A` (shard id: `16312`) and `orders/1-A` (shard id: `151326`). Using the shard allocation map in <<shard-replication-table>>, you can see that both
of them are going to reside in `Orders$0`. In this case, for all intents and purposes, they are going to be local to
one another. A query on `orders/1-A` that _includes_ the `Customer` property will not have to do any extra network
roundtrips to complete, for example.

.Why is RavenDB using the document id for sharding?
****
RavenDB uses the document id to determine what is the shard id of a document. You can customize that using
conventions like so: `orders/2-A$customers/1-A`. The question is why is that required? There are several
important reasons for this decision.

The most important issue is that we need to shard by _something_. If we would _not_ shard by document id,
we run the risk of writing the same document id to different nodes. This issue has plagued other databases
and can lead to subtle (and hard to recover from) errors. RavenDB's multi-master nature means that it
is entirely possible for two requests to be processed independently by two nodes in the cluster at the same
time, with no coordination required.

The fact that we can rely only on the document id to find the relevant shard means that we don't have to
worry about duplicate ids in different shards or fragile system setups. RavenDB's sharding design is a
natural extension of the rest of its distributed nature.

RavenDB also offers several features around document ids (`include`, `load` and graph queries, to name a few)
that greatly benefit from being able to go from a document id to a shard id. This allows the sharded database
to perform several important optimizations along the way.

RavenDB also offers a way to handle content based sharding, where the shard location is determined by the
content of the document. This is done the first time a document is stored in RavenDB (indicated by a `$`
suffix, such as `orders/1-A$`). RavenDB will use the user-defined content based sharding to determine
which shard this document should go to.

What is important to understand is that the client-supplied id of `orders/1-A$` will be mutated by the server
to create a new id that belongs to a specific shard. Assuming this order belongs to `customers/1-A`, the final
document id will be `orders/1-A$@982173`.

We'll cover content based sharding and the generated ids in depth later in this chapter.
****

These two documents, however, reside on different shards. That means that RavenDB is free to re-assign them to
different nodes if it so wishes. Documents that share the same shard id, on the other hand, are guaranteed to always
be placed together with one another.

I mentioned that RavenDB uses the hash of the document id to generate the shard id. But that isn't actually the full
story. RavenDB uses the following conventions for finding the shard based on the document id:

* If the document id has a `$@` followed by a number between 0 and 1048576, the shard id will be that number. This
  feature is used if we want to statically assign a document to a particular shard. The `$@<num>` feature is
  mostly used in content based sharding.
* If the document id has a `$` in it, take the string from the last `$` and use that as the value to hash to get the
  shard id. In other words, `orders/1-A$customers/1-A` will use `hash("customers/1-A")` to find the shard for this
  document.
* Otherwise, hash the entire document id to find the shard id.

It is important to understand that as far as RavenDB is concerned, the following are _all_ document ids:

* `orders/1-A$@982173`
* `customers/1-A`
* `orders/1-A$customers/1-A`

The _entire_ value (including the parts past the `$`) is the document id. The fact that the sharding
infrastructure assigns meaning to the `$` value isn't relevant for any other aspect of RavenDB. It is legal to have both:
`orders/1-A$@982173` and `orders/1-A$customers/1-A`. Note that in this case, both reside in the same shard, and that
is fine. They have different document ids.

When you store references between documents in your model, you'll use the document id (including the portion after the
`$`). This makes it possible to use features such as `include` or `load` efficiently. If you are on the same shard, the
operation is guaranteed to be local. If you are on the same fragment, the operation will be local (but there is no
guarantee that the value will remain on the fragment). If the value is on a different fragment, the sharding
infrastructure in RavenDB will fetch it from the relevant node for you.


### Content based sharding

Using document ids for sharding gives you a simple model that is easy to follow. The client can distribute the
documents fairly among the shards (by doing nothing, and letting RavenDB assign shards automatically). If you want
more control, you can use the `$` suffix option to control which shard a document should reside on.

The documents `customers/1-A` and `orders/1-A$customers/1-A` will reside on the same shard, as we have already
seen. In this section, I want to focus on what this _means_. The advantage of having related data reside in the same shard
is obvious. Data locality can improve performance significantly.

The question is how you achieve that goal without also getting into problematic issues with overly large shards. Another
aspect of sharding and controlling where a document would go is the issue of query optimization.

.Pre-requisite: RavenDB queries and RQL
****
In order to fully understand sharding, I'm going to go over RavenDB sharding behavior with queries. We have touched
this a little bit in <<document-crud>>, but the full discussion of queries in RavenDB is in the next part of the book.

I tried to discuss using simple queries that should be understandable without any background, but if you have any
questions about how RavenDB processes queries normally, you might want to skim through Part III and then come back
here.

Like most other aspects of sharding in RavenDB, the query behavior is a natural extension of how RavenDB handles
queries in the unsharded case.
****

Let's consider the following query: `from Orders where id() = 'orders/1-A'`. When you send such a query to a sharded
database, RavenDB can easily figure out that this document can only reside in `Orders$0` (the shard id is `151326` and that
is mapped to `$0`). The sharding infrastructure will forward the query to that particular fragment only.

On the other hand, if we are querying on the _content_ of documents, RavenDB has far fewer options. Consider this query,
instead: `from Orders where Customer = 'customers/1-A'`. Even though we have been careful to create all orders for
a customer with the `$` suffix (the document ids are: `orders/1-A$customers/1-A`, `orders/2-A$customers/1-A`), RavenDB
has no way to understand that. In order to process this query, RavenDB will have to talk to all the fragments in the
database.

This is where content based sharding comes into play. We can _teach_ RavenDB that a particular property (or properties)
should be accounted for during queries. Take a look at <<content-sharding-orders>>, where we give RavenDB enough information about
our sharding configuration to understand how it can better query the data.

[[content-sharding-orders]]
.Database configuration for content based sharding
[source,json]
----
"Sharding": {
  "ByContent": {
    "Orders": {
      "Fields": [
        "Customer"
      ]
    }
}
----

In <<content-sharding-orders>>, you can see that we provide a `ByContent` configuration for sharding. In particular, we tell RavenDB
that for the `Orders` collection, we'll shard the data by the `Customer` field. This humble configuration has quite a
few interesting results.

The most obvious one is that RavenDB is able to optimize this query: `from Orders where Customer = 'customers/1-A'`. Instead
of having to query all nodes in the database, RavenDB figures out what is the fragment that owns this query and uses that
alone.

.Smart content based sharding
****
When using content based sharding, for the most part, we are going to use the hash of the value you marked. However,
there are a few ways that you can modify this behavior. For example, if you want to shard by zip code, you can use:
`"Fields": ["Address.ZipCode"]`, which will use the hash of the zip code, or: `"Fields": ["numeric(Address.ZipCode)"]`
which will use the _numeric value_ of the zip code, instead. In this case, the specific field _must_ be a numeric value
and the value will be modulus with 1048576 to find the shard id.

When using dates, you can use the `ticks` function, like so: `"Fields": ["ticks(OrderedAt)"]`, which accepts a date time
value and modulus the `Ticks` of the date time value with 1048576 to find the shard id. This is useful if you want to get
time based sharding (but beware of creating hot spots).

An interesting case of content based sharding is using the `id()` function, like so: `"Fields": ["id()"]`. This is
identical to _not_ having any content based sharding and is mostly used while you are migrating between
sharding strategies.

You can find the full listing of available functions for content based shards in the online documentation.
****

There are other aspects for this configuration, however. We talked earlier about saving documents with an id that has `$` in
the end, such as `orders/1-A$`. Without a content based sharding configuration, such an operation would result in an error.
Document ids cannot end with `$` when using a sharded database.

_With_ such a configuration, RavenDB will hash the content of the `Customer` property and update the final document id. In
this case, we'll have `orders/1-A$@982173`. The `$@<num>` allow us to refer to a particular shard directly, without needing
to hash the value. This process occurs only on the very first time that you save a document (indicated by the fact
that your document id ends with `$`). The document id will change to its final form and RavenDB will return the new id to
the client. From the client side, you'll get the final document id only after the `SaveChanges()` call has been
successfully processed and returned.

Sometimes, you don't want to wait for the `SaveChanges()` to return. For example, you may want to modify multiple documents
in a single database transaction. For example, let's say that we want to write two documents: an `Order` (which needs to
reside in the same shard as its `Customer`) and a `ShippingManifest` that references the order but may live on another
shard entirely.

If we would save the `Order` document with the id `orders/1-A$`, the final id is generated on the server side. This means
that in order to save the `ShippingManifest`, we would need to first save the `Order`, get its new id and only then save
the `ShippingManifest`.

This is why you can also define the shard that will be used using `orders/1-A$customers/1-A`. That allows you to generate
the value completely on the client and use a single transaction to write the `Order` and the `ShippingManifest`. The `$`
suffix makes it easy to scope documents to their parent. You can also compute the hash of the shard directly, using:
`xxhash64( docId.ToLower() ) % (1024 * 1024)` and save the document as `orders/1-A$@982173` directly from the client.
Sometimes it is easier to use the actual value, though. This is especially the case if you are working with the data
directly, through the Studio.


#### Modifying fields with content based sharding

I mentioned that content based sharding configuration is applied when we save a new document that ends with `$`. At that
point, we look at the relevant fields and generate the right shard value. We can also use this knowledge during queries,
to optimize what fragments we need to look at.

An interesting question arises, though. What happens if we update the `orders/1-A$@982173` document so its `Customer`
will be `customers/2-B`? The short answer is that RavenDB will raise an error in this case. With content based
sharding in place, RavenDB will ensure that the shard of the document according to the configuration is fixed.
The shard id for `customers/2-B` is `2423`; because it doesn't match the current shard based on the document
id, and we have content based sharding, RavenDB will reject this as an invalid write.

Note that if we were to replace the `Customer` field in the document with `customers/741135-C`, on the other hand,
that _would_ work. This is because the shard id for `customers/741135-C` is also `982173`, so it is a valid value.

More importantly, this is going to be the case even if the full document id was `orders/1-A$customers/1-A`. RavenDB
validates only that the value of the content is the same shard, nothing else.

.What kind of sharding strategy is preferred?
****
I'm spending quite a lot of time describing how you can control what shard a document resides on, how RavenDB can
optimize queries and operations based on that, etc. I'm doing this primarily because this is something that you
_might_ need for specific scenarios.

If you can get away with it, having _no_ sharding strategy is probably the best. It means that RavenDB will fairly
distribute the data between the nodes in the cluster. Indeed, if you just use the RavenDB API to work with a
sharded database, that is exactly what will happen. The reason for having a sharding strategy is when you can
significantly benefit from it.

For example, in a `Customers` and `Orders` scenario, if most or all of the operations will always be in the scope
of a particular `Customer`, it may make sense to shard based on the customer id. However, if you are doing a lot
of operations across customers, there is no benefit to this kind of sharding strategy.

RavenDB allows you to alter the sharding behavior at runtime, without costly migrations, so it is well worth
remembering that it is hard to predict how the system will actually behave. In many cases, it is easier to modify
the system after you have actual operational experience with it.
****

The reason RavenDB performs this validation is to ensure that queries on those values can be properly optimized. If
we _didn't_ do this validation, you might end up with an order on shard `982173` whose `Customer` field is set to
`customers/2-B`. At this point, a query for: `from Orders where Customer = 'customers/2-B'` will be routed to a
different fragment and will find no results. In order to prevent this, we ensure that the value that you are
using for content based sharding matches the actual shard of the document.

That said, there are cases where you'll want to mutate the values you are sharding on. It is common for other sharded
database solutions to make the sharding strategy the first thing you'll define and set it in stone.
Making such immutable choices for your system early on usually leads to needing to change the system down the line,
once you have weathered production and seen how the system is actually being used.
At that stage, you typically need to do a full migration (which is a _costly_, complex operation, has high resource usage
and takes quite a bit of time).

In contrast, RavenDB's sharding strategy is built to be evolved on the fly. Let's consider the case of sharding
`Customers`. So far we assumed that we'll be spreading the customers across the shards evenly, but let's assume that
we have had a content based sharding configuration as shown in <<content-sharding-customers-bad>>. The configuration shown here is probably
a bad one, mind. We're intentionally setting things up badly to see how we can recover from operational mistakes.

[[content-sharding-customers-bad]]
.Content sharding using multiple fields for Customers (bad strategy)
[source,json]
----
"Sharding": {
  "ByContent": {
    "Customers": {
      "Fields": [
        "Address.State",
        "Address.City"
      ]
    }
}
----

The configuration in <<content-sharding-customers-bad>> shows how we can shard on multiple fields. Internally, we handle this by concatenating
all the field values and hashing the result. This configuration will put all users in the same `State` and `City` pairs
in the same shard. Just for the record, this is very likely a bad sharding strategy. If you have a lot of users from a
particular location, that is going to create a single big shard.

.Query optimization with multiple fields using content based sharding
****
RavenDB _can_ optimize queries on collections with multiple fields using content based sharding. However, it needs
to have _all_ the fields present in the query in order to do so (the order in which they appear is not relevant).

This is because RavenDB needs to hash all the fields for content based sharding in order to find the relevant shard
that applies for a particular query. In the case of the configuration in <<content-sharding-customers-bad>>, it means the following queries
on `Customers` will be able to take advantage of this optimization:

* Queries by id (which always know what shard to use).
* Queries that include _both_ `Address.City` and `Address.State`.

Queries that do not include these details will be processed normally and sent to all the possible fragments for answers.
****

But this configuration is also bad for another reason: it assumes that a customer can never change their `Address.State`
or `Address.City` fields. To be rather more exact, it means that a customer can only move to an `Address.State`/`Address.City`
pair that has the same shard id as the previous one. I think you'll agree that it is unreasonable for our application
to expect users to take the internal sharding architecture of your application into account when they decide where they should move.

Luckily, there is a solution for that. Let's look at <<content-sharding-mutable>>, where we have made a small but significant change to
the content based configuration. We have added the `"Mutable": true` option to the configuration.

[[content-sharding-mutable]]
.Allowing mutation of the fields forming the content based sharding
[source,json]
----
"Sharding": {
  "ByContent": {
    "Customers": {
      "Mutable": true,
      "Fields": [
        "Address.State",
        "Address.City"
      ]
    }
}
----

The configuration in <<content-sharding-mutable>> shows a mutable content based sharding. This is an interesting concept. It tells RavenDB
that if there are documents saved with ids that end with `$`, it should generate the full document id as usual. However,
because these fields are mutable, RavenDB also:

* Allows the user to modify these fields, regardless of what shard the content _should_ reside on.
* Content based sharding is applied only on the first save of the document, never on updates.
* RavenDB cannot rely on the value of these fields for the purpose of routing queries and has to disable sharded
  query optimizations.

You can start out with having a content based sharding without the `Mutable` flag, in which case RavenDB will enforce the
rules and optimize the queries. You can then set the `Mutable` flag and allow changing the sharded values. The purpose of
this feature is to allow you to do such changes _safely_. You lose on the sharded query optimizations, admittedly, but you
don't have to rebuild your entire database.

.Going from mutable to immutable content based sharding
****
RavenDB _allows_ you to have `"Mutable": true` and update this to `false`. However, it does *not* validate that the
underlying documents have content matching their allocated shard. This is done so you'll be able to go from immutable
to mutable (losing the benefit of optimized queries), modify your data at your leisure and then go back to immutable.
In such cases, it is the _operator's responsibility_ to ensure that the data matches RavenDB's expectations.
****

Changing the shard strategy is an online operation that can be done at any time. This makes it an operationally lightweight
option, and much more feasible as you evolve your data strategy. It is expected that you'll have several such evolutions as
your data and load grows. Obviously, if you can set things right from the get go, that is ideal, but I have found that
expecting perfection from the start is unrealistic. RavenDB's sharding is meant to be deployed in an imperfect world, and has
been designed explicitly to allow these kinds of changes over time.


#### Changing the fields for content based sharding

In the same way you can change the `Mutable` field, you are also able to change other aspects of content based sharding.
For example, you may have started sharding `Customers` by state and city, only to realize that this is a bad idea. You
can change that to sharding by zip code, instead. The process itself is straightforward, and mostly depends on whether you want
to try to get optimized queries or not.

* Set `Mutable` to `true` -- RavenDB now knows that it can't rely on content based sharding for the collection.
* Modify the fields that you want to use for content based sharding -- RavenDB will use this for all new documents.

_Existing_ documents, on the other hand, are unmodified and may reside in a different shard according to the new sharding
strategy. That is why we have had to set `Mutable` to `true`, after all.

At this point, you can leave the system as is, the new sharding strategy will apply for new documents and start adjusting
the weight of different shards. In many cases, the reason you want to change the sharding strategy is that your old strategy
created hot spots. Just changing the strategy (maybe by using the `id()` option) is usually enough to remove the hot spots
and put you in a better place.

At this point, queries and operations are going to proceed normally and this operation has no downtime requirement. You lose
the ability to optimize queries by the shard function (since this isn't how the database is currently organized). To get this
back, you can start a migration process, in which you'll locate the documents that need to move and re-write them.
Remember that you'll need to create _new_ documents, with different ids, to go to the new shards.

This migration process is also something that can happen in an incremental manner. When you are done updating the database,
you can set `Mutable` back to `false` and RavenDB will take into account the content of your queries when it is answering
them.

[IMPORTANT]
====
RavenDB does _not_ validate that the existing documents match the expected sharding strategy. It will validate
new or updated documents, but existing ones are not inspected. This means that it is the responsibility of the operators
to make sure that after migration, the sharding strategy applies. If in doubt, avoid setting `Mutable` to `false`.
====


#### Using a fuzzy sharding strategy

I spent a considerable amount of time talking about how you can ensure that two documents reside in the same shard. RavenDB
_guarantees_ that two documents that are on the same shard will always be on the same fragment. In other words, we ensure a
high degree of locality in this scenario.

That said, let's take an example of a cluster with 25 nodes in it. A sharded database with a replication factor of 2 means
that we have 13 fragments overall. However, RavenDB has `1048576` shards that are assigned to these 13 fragments, so each
one of those fragments hosts about 80 thousand shards. If we force documents to reside on the same shard, we may end up
having obese shards. But for the most part, if we just want them to reside on the same fragment, we can take another tack.

RavenDB generally assigns shard _ranges_ to a fragment, not individual shards. This means that shards that are near one
another are likely to be allocated on the same fragment. RavenDB allows you to define content based sharding that isn't
going to match exactly. Instead, we just need a rough match. Let's look at <<fuzzy-content-sharding>>, for such an example.

[[fuzzy-content-sharding]]
.Specifying fuzzy content based sharding
[source,json]
----
"Sharding": {
  "ByContent": {
    "Orders": {
      "Range": 1000,
      "Fields": [
        "Customer"
      ]
    }
}
----

<<fuzzy-content-sharding>> uses a new option, `Range`, and sets it to `1000`. I'm going to show first by example, then
explain in more detail. We'll go back to our old friend, `orders/1-A$` which belongs to `customers/1-A`.
Here are a few important numbers:

* `customers/1-A` assigned to shard `982173`.
* `orders/1-A` assigned to shard `151326`.

We specified a `Range` of `1000`, so the shard id that RavenDB will generate for this document will be `982326`. In other
words, the final shard for the document has to fall within a range of a thousand shards from `982173`.
In this case, RavenDB simply uses the first three digits from the content based sharding and the rest from the
document id we already got. If the `Range` was `10000` then the output would be `981326`, and so on.

The idea behind the `Range` is that we no longer _tell_ RavenDB what shard this document should be. We... suggest.
And we give enough leeway for RavenDB to manage it on its own.

In the case of `Customers` and `Orders`, assuming a `Range` of `1000`, each customer is going to have its orders located
on shards that are within 1,000 shards from the customer's shard. Because RavenDB allocates ranges to fragments, it also
means that there is a high likelihood (but no _guarantee_) that they will reside on the same fragment and have all the
locality benefits that you would expect.

RavenDB is able to use this information in queries as well. Consider the following query:
`from Orders where Customer = 'customers/1-A'`. RavenDB will hash the value, resulting in `982173`, it is then going to
send the query to all the fragments that contain shards in the range of `982000 .. 982999`.

In most cases, this is going to be just one fragment, but it is also possible that this range is allocated to two
fragments. Given that in our scenario (13 fragments, each with about 80,000 shards), it is unlikely that this range will span more than
two fragments.

.Increasing the Range property is a safe operation
****
Unlike most content based sharding changes, increasing the value of the `Range` property is a safe
operation to do. Let's assume that you started out with the shard configuration shown in <<content-sharding-orders>>. Over time, you realized that
some of your customers have a _lot_ of orders (congrats, what a great problem to have). You are running into issues
with an obese shard.

You can update your sharding configuration to the one shown in <<fuzzy-content-sharding>> _without_ having to set `Mutable` to `true`.
This is because <<fuzzy-content-sharding>> is a superset of <<content-sharding-orders>>. Any document that was valid under <<content-sharding-orders>> is also
valid under <<fuzzy-content-sharding>>.

What this means is that if you run into such issues with your sharding configuration, one of the first things to look at
is if you can simply increase the `Range` property of the sharding configuration. In many cases, this is all you need to
do.
****

In other words, using `Range`, RavenDB is able to narrow the cost of the query from all fragments to just one or two. It also
neatly avoids several issues around obese shards.

All the usual semantics of content based sharding still apply, mind. You have optimized queries, you cannot change the fields
specified in the sharding strategy to a value that doesn't match the shard range that this document is located on, etc.
You can always increase the `Range` value of the sharding configuration, so it doesn't require too much upfront thinking
about it. If you _haven't_ specified the `Range`, it is initialized to `1` by default (which effectively disables it).

The one important thing about `Range` that you must remember is that it turns a _guarantee_ of two documents always residing
in the same fragment to a _statistically likely scenario_. In other words, you can absolutely count on the fact that
_some_ of the `Orders` documents will reside in different fragments from their `Customer`. That won't happen to all
customers (it's likely a rare scenario, in fact), but that is something that you'll run into and have to account for.

But aside from the locality of using a single fragment, why does this actually matter? In terms of queries, you are
unlikely to notice any difference. There may be an additional network roundtrip between the nodes in the cluster, but that
isn't likely to matter much for you.

The most important change is around the system behavior. In particular, around certain types of advanced indexing operations
and most importantly, transactions.


### Transactions in a sharded database

RavenDB is a transactional database. That means that you can modify multiple documents at one time and save them all in an
atomic fashion (as well as durable, and the other ACID properties). These documents can belong to the same collection or
different collections. You can also have a transaction that spans documents, attachments, counters and time series.
This is true when we are talking about transactions for unsharded databases, at least. What is the status of things
when we are dealing with a sharded database?

A transaction in an unsharded database can have one of two modes. It can be a local transaction, which is committed on a single
node and utilizes RavenDB's multi-master nature to notify the other members in the cluster. Alternatively, it can be a
cluster-wide transaction. We discussed cluster-wide transactions vs. local transactions in <<ravendb-clusters>>, so you may want to
check there to remember what the relevant scenarios for each of them are.

For sharded databases, the situation is actually pretty much the same. RavenDB supports local transactions _and_
cluster-wide transactions for sharded databases. A cluster-wide transaction can span any number of shards and fragments and will be
applied as an atomic unit. Things get more interesting when we are talking about local transactions in a sharded
environment.

RavenDB ensures that a transaction that applies to multiple documents in the same shard will be atomic. The actual promise is a
bit stronger. A transaction that applies to multiple documents in the same _fragment_ is guaranteed to be atomic. However, we
don't guarantee that particular shards will always reside on the same fragment. RavenDB is free to move them as it sees fit.

What this means is that if you modify two documents on the same shard, you can rely on there being a single transaction
binding them together. If they are on different shards _and_ you are using a local transaction, that operation is not
necessarily going to be atomic.

As I said, the actual behavior is stronger than per-shard transactions, because a transaction actually applies at the
fragment level. However, I would not recommend relying on this fact. If you want a transaction that will span multiple
shards, it is best to use cluster-wide transactions.

A cluster-wide transaction is typically more costly than a local transaction, of course. That is one reason why you'll
typically want to place documents in the same shard if they are going to change together in a transactional manner.

.Fragments, nodes and database groups, oh my!
****
When using an unsharded database, we have a Database Group, a group of nodes that host the database in question and
replicate the data among themselves. When we are using a sharded database, we have fragments instead, but it may
be confusing to understand why we use this term and how it relates to the things we already know about RavenDB's
distributed nature.

A fragment _is_ a database group, for all intents and purposes. It doesn't have its own name, or its own configuration,
but it is a Database Group. It hosts a database instance that resides on multiple nodes, all of which are replicating
data to one another. The key distinction between them is that a fragment only holds... well, a fragment of the overall
data in the sharded database. All the fragments in a sharded database have the exact same configuration (indexes, ongoing
tasks, etc).

The only things that are different between the various fragments are their topologies (what nodes they reside on) and
the shard associations (which documents reside on which fragments).
****


### Static indexes and aggregation queries

RavenDB has two types of queries. The first you have already seen in this chapter, query on a collection, such as:
`from Orders where ...`. The second, on the other hand, queries an _index_ and looks like this:
`from index 'Orders/Totals' where ...`. We cover these in detail in Part III of the book. This section may not make much
sense to you at this point without understanding RavenDB indexes in general, so you might want to just make a note of this
and come back to it later. The interaction of indexes and sharding is quite important, as you can imagine. There are quite a
few options that I need to cover and I don't want to unnecessarily duplicate information that is already better explained
in context in the chapters about indexes. Instead, I'm going to refer to the features and their interaction with sharding
and let you complete the full picture at your own pace.

.Where do the indexes run?
****
RavenDB indexes are run at the level of the individual fragment, over the data local to that fragment. The sharding
infrastructure is responsible for querying the right fragments for the query, merging the results and returning a
result set that appears to have come from a single server.
****

A query such as `from index '<index name>'` is using an index that was defined by the user. Such indexes can do all _sorts_
of interesting things, such as run computation, aggregate data, index data from related documents, and more. The question is,
how do all these features work with sharding?

RavenDB attempts to make the process intuitive and simple for the default case, while giving you enough knobs to customize
the behavior per your needs. The first rule of indexes and sharding is that an index that operates on a single collection
will use, by default, the same sharding strategy as the collection it is covering.

In other words, the `Orders/Totals` index, which is covering the `Orders` collection, is going to be sharded by
RavenDB using the same manner as the `Orders` collection. Assuming that we have used content based sharding on `Customer`, then
any query on `Orders/Totals` that includes the `Customer` field will be directed to the specific fragment for that
`Customer`.

This is the case whether the index is a simple one or a map/reduce index (one that aggregates data). If the index has a
single `Map` (covering a single collection), it will default to the content based sharding strategy defined for
its source collection.

.Caveats for queries in a sharded environment
****
For the most part, you can run your queries as you would normally, and RavenDB will make it happen. There are a
few scenarios that you need to take into account that can have a significant performance impact.

First, paging, and in particular deep paging, when running a query that uses multiple fragments is likely going to
be slow. Consider the following query: `from Orders where OrderedAt > $today limit 10 offset 5000`.
This query is going to be _expensive_, but let's see why exactly this is the case, shall we?

This is a query on the `OrderedAt` field, which isn't sharded upon. This means that RavenDB needs to query all the
fragments for this query. The query also asks for a single page of 10 results, but 500 pages deep. In order to
properly answer this query, RavenDB needs to fetch 5,010 results from _all_ the fragments in the database.
It then needs to sort these results and select the 5000 .. 5010 results to return to the client.

Assuming we have 13 fragments, that means retrieving 65,130 results from all the servers, sorting them and
then returning just 10 to the client. That is a significant amount of work to go through. In general, it would be
better if you didn't allow such deep paging operations in a sharded environment.

Second, when issuing full text queries and ordering by the score of the matches, you need to be aware that the
score is actually computed on a per fragment level. The sharding infrastructure knows how to scale results from
different fragments, but it may have an impact on the order of the results.

Third, it is tempting to run queries such as: `from Orders group by Address.City select count(), Address.City` for
your aggregations. Such queries will _work_, but they require RavenDB to query all the fragments in the cluster.
It is often better to define a Map/Reduce index (discussed in Chapter 12) and ETL processes (discussed in the next
chapter) to push to a dedicated database. This gives you the best scenario. RavenDB will aggregate the data on each fragment
independently, then push it to a single location, where it will be aggregated again.

That final aggregation is likely to be _much_ smaller and can reside on a non-sharded database. That means that the cost
of providing the information is drastically lower. We'll discuss such a scenario later in this chapter.
****

This convention means that you generally don't need to think about sharding for indexes -- they are already going to work
as you expected them to. If the sharding fields are in the query, they will be used to optimize the query. Otherwise,
we'll send the query to all the fragments. From experience, when using sharding, you will naturally include the sharding
fields in your index. It _is_ important to make sure that you use the same field name as the source collection, of course.

As you can probably tell from the emphasis, indexes can cover more than a single collection. At this point, RavenDB has no
idea which of the collections' sharding strategy to apply. In this case, it isn't going to attempt to guess -- you are going
to have to tell it. Let's look at <<index-shard-strategy>>, which shows how this is done.

[[index-shard-strategy]]
.You can define a shard strategy on indexes as well as collections
[source,json]
----
"Sharding": {
  "ByContent": {
    "Orders": {
      "Fields": ["Customer"]
    },
    "Orders/Totals": {
      "Fields": ["CustomerId"]
    },
}
----

<<index-shard-strategy>> shows how you can define content based routing on an _index_, as well as a collection. In this case, we tell
RavenDB that any queries on the index `Orders/Totals` should treat the `CustomerId` field as the shard field. This feature
is useful for several scenarios.

In the case in <<index-shard-strategy>>, we renamed the `Customer` field to `CustomerId`. If we have a multi-map index (which covers
multiple collections), we use the same technique to tell RavenDB which field(s) it should consider for content based sharding.


#### Indexing related documents

An advanced feature available for RavenDB indexes is the ability to index a document using a _related_ document's data.
For example, in the case of `Employees`, you can index the `Employee`'s _manager_ name in the index.
This topic is covered in depth in Chapter 11, but a quick example of how this looks can be seen in <<load-document-index>>.

[[load-document-index]]
.Getting values from a related document at indexing time
[source,csharp]
----
from e in docs.Employees
let manager = LoadDocument(e.ReportsTo, "Employees")
select new // data to index
{
    e.FirstName,
    e.LastName,
    ManagerFirstName = manager.FirstName,
    ManagerLastName = manager.LastName
}
----

With sharded databases, you can only index related documents (using `LoadDocument` or `load` calls from the index) on documents
that reside in the same shard as the document you are indexing. In other words, you can only index the `Employee`'s manager if
the manager is also located on the same shard as the `Employee`.

This limitation applies to _shards_, not to fragments. Even if the related document is physically located in
the same fragment as the document that is being indexed, if they are not on the same shard, calling `LoadDocument` would
fail. Note that for this limitation, the `Range` specification is not relevant. An exact match on the shard is required; a
range is not sufficient.

Luckily, this feature is already used primarily for data that is already very strongly tied together, so if you need to do so,
it is already very likely to be bound to the same shard.


#### Map/Reduce indexes

RavenDB indexes are used to... well, find stuff. That is their primary purpose, as you would expect. They are also used for
a very different purpose, however. They are the backbone of aggregating information. The whole of Chapter 12 is dedicated to
these types of indexes, called Map/Reduce indexes, so I'm not going to discuss them here. For now, all you need to know is
that they allow you to run data aggregation _very_ cheaply.

This is the case when we are talking about an unsharded environment, but what about a sharded database? As with other indexes,
you can define a content based sharding and RavenDB will optimize your aggregation queries as usual. However, what will
happen if you need to do an aggregation query on a data set that spans multiple fragments? Let's consider <<index-range-sharding>>
as a good example.

[[index-range-sharding]]
.Using range specification for indexes
[source,json]
----
"Sharding": {
  "ByContent": {
    "Orders/ByCustomer": {
      "Range": 1000,
      "Fields": [
        "Customer"
      ]
    }
}
----

The index `Orders/ByCustomer` is sharded on the `Customer` field, and we have the same `Range` specification we saw before.
A query such as: `from index 'Orders/ByCustomer' where Customer = 'customers/1-A'` will be processed by the sharding
infrastructure as usual. We'll find the relevant ranges for this query, and the fragments that they reside on. In this
case, let's say that this particular query touches two separate fragments. RavenDB will query both fragments for their results and
then _merge_ them, including re-aggregating the data from the various fragments into a single whole. Once
that data from all fragments has been aggregated, we'll apply sorting and paging and then return it to the client.

.Filtering is only applied once
****
An interesting caveat of the way RavenDB behaves is that it applies the filtering logic once, at the fragment level.
The sharding infrastructure will aggregate the data again, sort and page it, etc. What it will _not_ do is re-apply
filtering for the results.

Let's inspect a scenario where this can cause some issues. We have the following query:
`from index 'Orders/ByCustomer' where Count < 10 limit 2`, which requires us to fetch data from multiple fragments.
We get a result with a `Count` of 7 from `Orders$7` and `Count` of 4 from `Orders$8`. RavenDB will
re-aggregate the data, giving us a `Count` with a value of 11.

The reason RavenDB behaves in this manner is simple. Let's say that we'll apply the filter after the aggregation, that
means that we'll filter results for the query. Notice that this query has a `limit 2`, so we got only two results from
the fragments. We'll now need to go back to the fragments and ask them for more results, which may also be filtered,
etc.

This can turn _very_ expensive very quickly; see also the discussion on deep paging earlier in the chapter. Because this is
a rare scenario, with devastating consequences if triggered, RavenDB only runs the filters on the fragment level and not
at the sharding infrastructure.
****

Map/Reduce indexes and aggregation queries in a sharded environment work great if the number of fragments that they need
to use is limited. There are other ways to handle aggregation in a sharded environment; see the section about sharding and
ETL later in this chapter.


### Sharding and ETL

In a sharded database, it is common for most operations to follow the sharding strategy you defined, except that _certain_
tasks require you to go across the shards. This is felt most painfully when you need to run aggregations across the
entire data set.

Let's assume that we have the `Customers` and `Orders` scenario with 13 fragments across 25 nodes. Figuring out how many
orders a particular customer has is going to be trivial. RavenDB is going to be able to use a Map/Reduce index to pull
the aggregate data from one or two fragments.

However, if you want to show the number of sales for each product, that is a much more expensive operation. Conceptually,
it is identical to the query by `Customer`, but in this case, we can't lean on the sharding strategy. We have to touch all
the nodes to answer such queries, and that can be expensive.

Instead, we can combine two separate features of RavenDB to come to a very elegant result. Artificial documents and RavenDB
ETL together give us a very nice way to handle this kind of requirement. Let's go over the skeleton of the solution.
We cover artificial documents in detail in Chapter 12 and ETL is discussed in the next chapter. I don't intend to repeat
that information, but give you the information required to piece these separate features together into a complete solution.

You can define a Map/Reduce index and set its `Output Collection` value. This setting will cause the index to create an
artificial document whenever there is a new update to the index. These documents reflect the aggregated status of the index.
The key here is that these are real documents, which you can operate on using other RavenDB tools -- and in this case, the
RavenDB ETL feature.

Be aware that the documents will _always_ be written to the fragment where they were indexed. Make sure to set up the proper
content based sharding to ensure that RavenDB knows where to find the artificial documents. But the most common use for
these artificial documents is to allow us to operate on them using the ETL processes.

RavenDB ETL allows you to define an ETL process that would copy documents from one database to another. Unlike replication,
where the entire state of the database is cloned to the other side, ETL allows you to define exactly what collections,
documents and data will be sent to the other side.

The underlying idea is to set up Map/Reduce indexes to generate artificial documents, and then push these documents to
another location, typically a single database. The idea is that the Map/Reduce operation has already significantly...
reduced the amount of data that we are working on, so there is no issue pushing it to a single location.

At that point, you can aggregate the resulting data again using additional means, but the dataset you are working on is
already much smaller, and the existing Map/Reduce indexes and RavenDB ETL processes will keep the data up to date as changes
happen on the cluster.

.Ongoing tasks in a sharded database
****
RavenDB has the concept of ongoing tasks, such as RavenDB ETL, Subscriptions, backups, etc. These tasks can be defined
at the database level and will be tasked to a particular node in the database group. In a sharded environment, they work
in pretty much the same manner.

The sharding infrastructure is going to apply any ongoing task on a sharded database to each of the fragments, as needed.
For example, if you have an ETL process set up, it will run (concurrently) on all the fragments in the sharded database.
****

Going back to the example of finding out how many sales we have per product, we'll not try to compute that by asking
each fragment in turn. Instead, we'll define a Map/Reduce index to run this aggregation and an ETL process to push this data
to another (unsharded) database. Each fragment will push the data from its own store to the same location, giving us a
global view of the system. At this point, instead of having to deal with the number of orders (tens / hundreds of
millions), we have to deal with a record per _product_, a much smaller number.

We can then apply additional Map/Reduce operations to gather the information we want from the summary. It's a good idea to
do just the required level of aggregation on the fragments before sending the data out. Just enough so the data size will
not overwhelm the destination. This approach gives us the chance to run more aggregation at the destination, across
multiple dimensions.

This method isn't really part of the sharding behavior of RavenDB; it is simply a useful approach to dealing with a common
problem. I've given only the higher level view for this. You can read the full details about Map/Reduce artificial documents
in Chapter 12 and about ETL in the next chapter.


### Dynamic load and data distribution

This section details how RavenDB actually manages the shards in a sharded database. So far in this chapter, we talked about
how RavenDB allows you to read and write data on top of multiple fragments seamlessly. We assumed that the shard allocation
is static and unchanging for most of the discussion. This isn't the case, however. RavenDB may (and frequently will) balance
the load and the data across various nodes in the system. Let's see exactly how it does this and what the implications
are for your operations and code.

****
RavenDB's shard rebalancing is fairly sophisticated. There are quite a few factors that impact it and this section is meant
to give you a good idea about what RavenDB is doing and how it goes about spreading data and load on the system. It isn't
meant to be a detailed implementation walkthrough. The full details of RavenDB's behavior can be found in the online
documentation.
****

When you create a sharded database, RavenDB defaults to simply dividing the overall shard range (0 .. 1048576) between the
fragments that were specified. If we have 5 fragments in the sharded database, each will be assigned a range of roughly
200 thousand shards. Remember that the reason we have so many shards is that we'll have about 1 MB per shard for each TB
of data in the overall database, assuming uniform distribution of data among the shards.
The idea is that a shard is likely to be small enough that it will take very little effort to move it between fragments.

Operators can choose to let RavenDB adjust the sharding ranges on the fly (moving shards between fragments). If you disable
automatic shard rebalancing, you need to make sure that the data distribution in your fragments remains within the
desired capacity. You may want to disable RavenDB from doing shard rebalancing if you have a sharding topology that includes data
locality. For example, if you have a sharded database that is geo-distributed, with fragments in New York and in London.

In such a scenario, you'll have set up the content based sharding and shard allocation map so documents will go to their
nearest fragment. You obviously don't want to move a shard between New York and London, so this is a good candidate for
disabling automatic rebalancing.

For most cases, however, you can give RavenDB free reign with moving the shards around to get the proper balance.

To facilitate this behavior, RavenDB tracks, on a per fragment basis, the overall fragment size and the size of each
shard assigned to this fragment. This can be very helpful to figure out if you have an issue
with your content based sharding strategy. The information is also used to decide how to rebalance the load in the sharded database.

RavenDB favors stability and steady state behavior over spikes in activity. Because of that, it will constantly monitor the
allocation of data across the sharded database and act whenever there is a sufficient imbalance between the fragments.
In particular, if there is a greater than 5% or over 1 GB difference in the size of neighboring fragments.

This probably requires some explanation. RavenDB uses the 5% or 1 GB difference to ensure that the _rate_ at which we'll
need to move shards between fragments is relatively constant. We don't want a shard move to be something that happens
only very rarely. Rare events are recipes for failures. But something that happens all the time? We are ready for it and
are used to dealing with its impact.

RavenDB also attempts to maintain the number of shard ranges relatively constant. This means that we'll usually move data
only to neighboring fragments. Assuming we have a 5 fragment database, shards can move from `$2` to either `$1` or `$3`,
but will not usually move to `$0` or `$4` directly. The idea is that we want to smooth out spikes in moving the data, with
the shards slowly migrating between the fragments in a predictable manner.

Let's consider the following shard allocation map, and how rebalancing will work in practice:

* `Orders$0` -- shards `0` - `349525`.
* `Orders$1` -- shards `349525` - `699050`.
* `Orders$2` -- shards `699050` - `1048576`.

If `Orders$0` is sufficiently larger than `Orders$1`, we'll need to move some shards over, to rebalance. This is done
by scanning `Orders$0` from `349525` backward, finding enough shards to move to `Orders$1` to make a difference.
Let's say that we decided to move 100,000 shards from `Orders$0` to `Orders$1`. After the move, we'll have the following map:

* `Orders$0` -- shards `0` - `249525`.
* `Orders$1` -- shards `249525` - `699050`.

In order to reduce operational instability, RavenDB will rarely engage in large scale moves. Instead, we'll be applying
constant corrective action. A typical shard move is limited to a few MB, small enough that it can be done
without putting too much burden on the sharded database.

RavenDB will also allow only a single shard move to be in progress between any two fragments. Again, the overriding logic
is to reduce, as much as possible, the overhead of the process.


#### Range splits and complex moves

When a fragment becomes too large and we need to move some data to other fragments, we will start by scanning the
edges of the fragments, to see if we can gather enough data to move to another fragment. However, what happens if the shard at the
very start (or the very end) of the range is very large?

Consider shard `699050`, allocated to `Orders$2`. If this shard is too big (over 128 MB, by default), we are probably better
off _not_ moving it. In this case, we'll attempt to look at the other side, which in this case is shard `1048576`. If we can
move the data from the end to the next fragment, RavenDB will go that way to avoid doing range splits. However, if on both
ends of the range in the fragments we have large shards and this fragment is too big, we'll do a range split.

A range split is a simple process, involving only the sharding metadata. After such a split, here is what the shard
allocation map for `Orders$2` will look like:

* `Orders$2` -- shards `699050` - `873813`.
* `Orders$2` -- shards `873813` - `1048576`.

Instead of having a single range for the fragment, we'll have two of them. Now we can start moving the shards around
`873813` as well (both up and down from it). In this case, because both ranges are assigned to the same fragment,
we'll now allow moving the new shards to any other fragment in the sharded database, not just to neighboring ones.
RavenDB will typically select the smallest fragment to start moving the data over.

Operators can also initiate a range split (or merge) directly. Typically when adding a new fragment to the database,
you'll initiate a few range splits to help RavenDB re-assign the shards to the new fragments more quickly, rather than
allow it to flow across all the fragments as it would usually.

// TODO: explain where this history can be seen.


#### How RavenDB moves a shard

We covered the process of how RavenDB decides to shift shards between fragments, but we didn't talk about how the process
actually works. As it turns out, there is actually quite a bit of work required to handle this scenario, at all levels of
the sharding infrastructure.

For now, let's assume that we want to move shard `349525` from `Orders$0` to `Orders$1`. One of the reasons that RavenDB limits
the size of shard moves is that we want the process of moving the shard(s) to be as fast as possible. Repeating the process
as many times as necessary in order to actually balance the data among the various fragments in the database.

The move process is composed of the following steps:

1. The cluster marks shard `349525` as in transit from `Orders$0` to `Orders$1`.
2. One of the nodes in fragment `Orders$0` will send the shard to `Orders$1`.
3. Fragment `Orders$1` will inform the cluster that the move has been made.
4. The cluster now considers the move process complete.
5. Fragment `Orders$0` will delete the shard's data locally.

RavenDB is a distributed database and we have to account for failures and partitions at every stage of the process.
There are quite a few interesting edge cases along the way. For example, what happens to writes to this shard while this process
is running? What happens if there is a failure of the destination midway through the move process?

Fragment `Orders$0` will send all the relevant data for the shard to `Orders$1`. While this is going on, a query that
touches both fragments may actually get the same document from both fragments. This is expected and handled; the
sharding infrastructure will use the document version that it got from the fragment that owns the shard at that point.

Any writes to the source fragment during this process will be sent to the destination, until there is no more data that
hasn't been sent to the destination on the source fragment. Once that happens, the source fragment will start rejecting
operations on that shard, letting the sharding infrastructure know that it needs to use the destination from now on. Until that
point, any failure would simply cause the process to be restarted. From that point, the move has been completed
and the only remaining task is cleanup.

.Aggregated results during moves
****
The sharding infrastructure is capable of filtering results that come from fragments that are not yet (or no longer)
owning the shard. This is done by comparing the document id of the result with the owning fragment and removing data
that doesn't match the shard allocation map. This process is sufficient when we are dealing with queries that operate
on single documents.

For aggregation, the situation is more complex. A document for a particular order may exist in two fragments at the
same time for the duration of the move. An aggregation query that touches both fragments may include this order twice.
At the sharding infrastructure level, there is no longer a document id that we can filter by, however. Therefore, an
aggregation query (a Map/Reduce operation) may give duplicated results during a move.

In order to handle that scenario, RavenDB uses the `IsStale` indicator for all queries that touch fragments that are
in the process of a shard move (incoming or outgoing). This ensures that your query accurately reflects the state of the
system and allows you to deal with such a scenario using the standard RavenDB measures.

You need to be aware of this behavior because it may cause the queries to remain stale for an extended period of time,
depending on how long it will take to complete the move. For this reason, among others, RavenDB attempts to make moves
only on small sets of data and do this iteratively, rather than in big batches.
****


### Summary

Sharding is a complex and fascinating topic, which we have spent a _lot_ of time thinking about. I tried to strike a balance
between giving you sufficient information to build a system on top of sharded RavenDB while not overwhelming you with
implementation details that are not relevant to you as a user.

We covered how RavenDB's sharding is layered on top of the distributed architecture that we talked about in the previous chapters.
In particular, a fragment in a sharded database can be thought of as a standalone database, just managed by the sharding
infrastructure. That means that high availability and replication are there, just as they would be in a normal RavenDB
database, and following the same rules that you are already familiar with.

RavenDB sharding operates by hashing the document ids (with some fancy moves thrown in to allow for content based sharding)
and assigning each document to a shard id between 0 and 1048576. These shards are then split into ranges and allocated to
fragments. RavenDB will manage the allocation of shards to fragments and use the allocation information to route documents
and queries to the right location.

Content based sharding allows you to define sophisticated sharding strategies based on your needs. RavenDB's approach allows
you to modify the sharding strategy on the fly, without incurring the high costs you'll find with other solutions. The system
allows you to ignore sharding entirely and let RavenDB do what it will, or to control exactly where each document will go,
and anywhere in between.

The common usage is to ensure that documents that are often accessed and modified together will reside in the same shard. You
can ensure that this is the case by using document id conventions or by defining content based sharding. Documents on the
same shard are guaranteed to be on the same physical location and can participate in an atomic local transaction. For scenarios
where you want to modify multiple documents in different shards, you can use a cluster-wide transaction, which allows for
cross-shard transactions.

We also covered how RavenDB's indexes work in a sharded environment. The indexes can inherit their behavior from their source
collection or you can define the content based sharding for each index independently. Queries on a sharded database will be
optimized if possible and routed to a single fragment for answers. If they can't be dealt with on a single fragment, RavenDB
will send them to all the relevant shards and combine the answers from the fragments to give you the right final result.

The same behavior also applies for Map/Reduce indexes, used for aggregating data inside RavenDB. The sharding
infrastructure is capable of merging and re-aggregating the data from multiple sources, coming to the correct tally across the
entire sharded database.

For certain types of queries, this is a great feature, but if most of your aggregated queries are running contrary to your
sharding strategy, you are probably better off with using the approach outlined in the last section. Do a minimal level of
aggregation on the fragment level, and then use ETL to push that to a central location for additional processing.
Incidentally, this is the exact topic of the next chapter.
